"""add status and updated_at to alerts

Revision ID: 2e15d222277a
Revises: 41bf261af532
Create Date: 2026-01-16 12:06:31.289338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e15d222277a'
down_revision: Union[str, Sequence[str], None] = '41bf261af532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('status', sa.String(length=16), server_default='open', nullable=False))
    op.add_column('alerts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('alerts', 'group_key',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.create_index('ix_alerts_group_key_created_at', 'alerts', ['group_key', 'created_at'], unique=False)
    op.create_index('ix_alerts_rule_id_created_at', 'alerts', ['rule_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index('ix_alerts_rule_id_created_at', table_name='alerts')
    op.drop_index('ix_alerts_group_key_created_at', table_name='alerts')
    op.alter_column('alerts', 'group_key',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('alerts', 'updated_at')
    op.drop_column('alerts', 'status')
    # ### end Alembic commands ###
