"""add group_key to alerts

Revision ID: 41bf261af532
Revises: b1b85630457f
Create Date: 2026-01-16 10:42:15.792162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41bf261af532'
down_revision: Union[str, Sequence[str], None] = 'b1b85630457f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('group_key', sa.String(length=128), server_default='', nullable=False))
    op.create_index(op.f('ix_alerts_event_id'), 'alerts', ['event_id'], unique=False)
    op.create_index(op.f('ix_alerts_group_key'), 'alerts', ['group_key'], unique=False)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_group_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_event_id'), table_name='alerts')
    op.drop_column('alerts', 'group_key')
    # ### end Alembic commands ###
