"""add threshold to rules

Revision ID: b1b85630457f
Revises: 3099c4ee7f79
Create Date: 2026-01-15 18:41:56.716623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b85630457f'
down_revision: Union[str, Sequence[str], None] = '3099c4ee7f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('threshold_count', sa.Integer(), nullable=True))
    op.add_column('rules', sa.Column('threshold_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'threshold_seconds')
    op.drop_column('rules', 'threshold_count')
    # ### end Alembic commands ###
