"""add throttle_seconds to rules

Revision ID: cbd8e2a0c1fe
Revises: d841bcb4d197
Create Date: 2026-01-15 17:25:24.518982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd8e2a0c1fe'
down_revision: Union[str, Sequence[str], None] = 'd841bcb4d197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('throttle_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'throttle_seconds')
    # ### end Alembic commands ###
